### PR TITLE
Fix included not being correctly parsed

### LINKED ISSUE #2: Fetching a resources with included resources is not working
### Description

```ruby
user = User.find("1", include: "posts")

# ArgumentError: wrong number of arguments (given 0, expected 1)
# from /Users/pablocrivella/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/jsonapi-resource-00e435daffcf/lib/jsonapi/resource/parser.rb:81:in `parse_relationship_to_many'
```

### PR DESCRIPTION
**Pull request by pablocrivella**
Fixes #2

### CODE REVIEW

File: spec/jsonapi/resource/parser_spec.rb [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+        {
+          id: "1",
+          comments: [parsed_comment1, parsed_comment2],
+          relationships: {
+            comments: JSONAPI::Types::Relationship.new(data: [comment1, comment2])
+          },
+          persisted: true
+        }
+      end
+      let(:parsed_user2) { { id: "2", persisted: true } }
```
Comment (rjclaasen) [inline spec/jsonapi/resource/parser_spec.rb]: How do you feel about moving some of the `let(:__2)` calls to the `context "when document data is an array do` block? Or maybe adding some newlines to distinguish related sets of `let`s, i.e. between `let(:document)` and `let(:user1)`.
I feel like it might improve the readability of all these `let` blocks and make it more clear which is used where.

File: spec/jsonapi/resource/parser_spec.rb [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+
+      context "when document data is an array" do
+        let(:data) { user1 }
+
+        it { is_expected.to eq(parsed_user1) }
+      end
+
+      context "when document is a resource" do
+        let(:data) { [user1, user2] }
```
Comment (rjclaasen) [inline spec/jsonapi/resource/parser_spec.rb]: It looks like `"when document data is an array"` and `"when document is a resource"` are swapped.

File: spec/jsonapi/resource/parser_spec.rb [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+
+    context "when document is a JSONAPI::Types::Success" do
+      let(:included_comment1) { { id: "1", type: "comments", attributes: { body: "Hi!" } } }
+      let(:included_comment2) { { id: "2", type: "comments", attributes: { body: "Hello!" } } }
+      let(:included) { [included_comment1, included_comment2] }
+      let(:document) { JSONAPI::Types::Success.new(data: data, included: included) }
+      let(:user1) { { id: "1", type: "users", relationships: relationships } }
+      let(:user2) { { id: "2", type: "users" } }
+      let(:comment1) { { id: "1", type: "comments" } }
+      let(:comment2) { { id: "2", type: "comments" } }
```
Comment (rjclaasen) [inline spec/jsonapi/resource/parser_spec.rb]: How do you feel about replacing this with
```ruby
let(:comment2) { included_comment2.slice(:id, :type) }
```

I feel like it might make the relationship between these two variables more clear.

File: spec/jsonapi/resource/persistence_spec.rb [hunk 4]
```diff
@@ -164,5 +164,22 @@
...
+          data: {
+            id: user.id,
+            type: user.class.type,
+            attributes: { email: user.email }
+          }
+        }
+      end
+      let(:user_relationships) { { profile: {} } }
+
+      it "removes the relatioships key from the hash" do
```
Comment (rjclaasen) [inline spec/jsonapi/resource/persistence_spec.rb]: Minor typo: relatio**n**ships

How do you feel about explicitly stating which hash the relationships key is removed from?
Or maybe `it "returns a hash without the relationships key"` to make it more consistent with the `it` block above this one?
